name: sync esp32 firmware
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  get_new_firmware:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: git clone https://github.com/ste7anste7an/micropython_ulab_lvgl
      run: git clone https://github.com/ste7anste7an/micropython_ulab_lvgl
    - name: copy build firmware
      run: |
        ls -l MicroPython/ESP32/
        cp micropython_ulab_lvgl/build/firmware* MicroPython/ESP32/
        ls -l  micropython_ulab_lvgl/build/firmware*
        ls -l MicroPython/ESP32/
        git config --global user.name 'Ste7an'
        git config --global user.email 'ste7anste7an@users.noreply.github.com'
        git add MicroPython/ESP32
        git status
        #git diff --exit-code || 
        git diff --exit-code || git commit -m "Synced with latest build"
        git push
    
